import { v4 as uuidv4 } from "uuid";

export const CardArr = [
  {
    id: uuidv4(),
    name: "Jasmin Noir",
    subname: "By Jasmin",
    productName: "eau de toilette",
    price: "20.00",
    offerprice: "20.00",
    img: "/assets/images/products/product1.png",
    ratingcolor: "#FF5894",
    rating: "4.5",
    totalReviews: "233",
    latestArrival: true,
  },
  {
    id: uuidv4(),
    name: "Jasmin Noir",
    subname: "By Jasmin",
    productName: "eau de toilette",
    price: "211.00",
    offerprice: "322.00",
    img: "/assets/images/products/product2.png",
    ratingcolor: "#FF5894",
    rating: "4.5",
    totalReviews: "233",
    latestArrival: false,
  },
  {
    id: uuidv4(),
    name: "Jasmin Noir",
    subname: "By Jasmin",
    productName: "eau de toilette",
    price: "122 .00",
    offerprice: "320.00",
    img: "/assets/images/products/product3.png",
    ratingcolor: "#FF5894",
    rating: "4.5",
    totalReviews: "233",
    latestArrival: true,
  },
  {
    id: uuidv4(),
    name: "Jasmin Noir",
    subname: "By Jasmin",
    productName: "eau de toilette",
    price: "120.00",
    offerprice: "320.00",
    img: "/assets/images/products/product4.png",
    ratingcolor: "#FF5894",
    rating: "4.5",
    totalReviews: "233",
    latestArrival: false,
  },
  {
    id: uuidv4(),
    name: "Jasmin Noir",
    subname: "By Jasmin",
    productName: "eau de toilette",
    price: "120.00",
    offerprice: "320.00",
    img: "/assets/images/products/product4.png",
    ratingcolor: "#FF5894",
    rating: "4.5",
    totalReviews: "23",
    latestArrival: false,
  },
  {
    id: uuidv4(),
    name: "Jasmin Noir",
    subname: "By Jasmin",
    productName: "eau de toilette",
    price: "120.00",
    offerprice: "320.00",
    img: "/assets/images/products/product4.png",
    ratingcolor: "#FF5894",
    rating: "4.5",
    totalReviews: "2",
    latestArrival: false,
  },
  {
    id: uuidv4(),
    name: "Jasmin Noir",
    subname: "By Jasmin",
    productName: "eau de toilette",
    price: "120.00",
    offerprice: "320.00",
    img: "/assets/images/products/product4.png",
    ratingcolor: "#FF5894",
    rating: "4.5",
    totalReviews: "",
    latestArrival: false,
  },
  {
    id: uuidv4(),
    name: "Jasmin Noir",
    subname: "By Jasmin",
    productName: "eau de toilette",
    price: "120.00",
    offerprice: "320.00",
    img: "/assets/images/products/product4.png",
    ratingcolor: "#FF5894",
    rating: "4.5",
    totalReviews: "1",
    latestArrival: true,
  },
];
