
export const CartArr = [
  {
    id: 1,
    name: "Jasmin Noir",
    subname: "By Jasmin",
    productName: "eau de toilette",
    price: "20.00",
    offerprice: "20.00",
    img: "/assets/images/products/product1.png",
    ratingcolor: "#FF5894",
    rating: "4.5",
    totalReviews: "233",
    latestArrival: true,
    productweight: "50ml",
    offer: "90% Off",
    tag: "#New Arrivals",
  },
  {
    id: 2,
    name: "Jasmin Noir",
    subname: "By Jasmin",
    productName: "eau de toilette",
    price: "211.00",
    offerprice: "322.00",
    img: "/assets/images/products/product2.png",
    ratingcolor: "#FF5894",
    rating: "4.5",
    totalReviews: "233",
    latestArrival: false,
    productweight: "100ml",
    offer: "40% Off",
    tag: "",
  },
  {
    id: 3,
    name: "Jasmin Noir",
    subname: "By Jasmin",
    productName: "eau de toilette",
    price: "122 .00",
    offerprice: "320.00",
    img: "/assets/images/products/product3.png",
    ratingcolor: "#FF5894",
    rating: "4.5",
    totalReviews: "233",
    latestArrival: true,
    productweight: "50ml",
    offer: "",
    tag: "",
  },
  {
    id: 4,
    name: "Jasmin Noir",
    subname: "By Jasmin",
    productName: "eau de toilette",
    price: "120.00",
    offerprice: "320.00",
    img: "/assets/images/products/product4.png",
    ratingcolor: "#FF5894",
    rating: "4.5",
    totalReviews: "233",
    latestArrival: false,
    productweight: "50ml",
    offer: "10% Off",
    tag: "#Top Seller",
  },
];
